-- Baseline schema: matches the JPA entities exactly (the schema that Hibernate
-- ddl-auto previously created). Flyway owns the schema from here on.
--
-- Conventions:
--   * Every id is a UUID generated by the application (GenerationType.UUID), so
--     no database-side default is needed -- raw SQL import scripts must supply ids.
--   * Instant fields map to TIMESTAMP WITH TIME ZONE (TIMESTAMP WITH TIME ZONE).
--   * Enums are stored as VARCHAR with CHECK constraints.
--   * votes.votable_id, reports.target_id and notifications.comment_id are
--     polymorphic/denormalised and intentionally have NO foreign key.

CREATE TABLE users (
    id                      UUID PRIMARY KEY,
    name                    VARCHAR(255)  NOT NULL,
    email                   VARCHAR(255)  NOT NULL,
    password_hash           VARCHAR(255)  NOT NULL,
    display_mode            VARCHAR(16)   NOT NULL,
    notify_on_review_reply  BOOLEAN       NOT NULL,
    notify_on_comment_reply BOOLEAN       NOT NULL,
    created_at              TIMESTAMP WITH TIME ZONE   NOT NULL
);

CREATE UNIQUE INDEX uk_users_email ON users (email);

CREATE TABLE restaurants (
    id          UUID PRIMARY KEY,
    name        VARCHAR(255)  NOT NULL,
    address     VARCHAR(255)  NOT NULL,
    cuisine_type VARCHAR(255),
    price_range VARCHAR(255),
    city        VARCHAR(255)  NOT NULL,
    avg_rating  DOUBLE PRECISION NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE   NOT NULL
);

CREATE TABLE reviews (
    id            UUID PRIMARY KEY,
    user_id       UUID NOT NULL REFERENCES users (id),
    restaurant_id UUID NOT NULL REFERENCES restaurants (id),
    rating        INTEGER NOT NULL,
    content       TEXT NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    edited_at     TIMESTAMP WITH TIME ZONE
);

CREATE TABLE comments (
    id                UUID PRIMARY KEY,
    review_id         UUID NOT NULL REFERENCES reviews (id),
    user_id           UUID NOT NULL REFERENCES users (id),
    parent_comment_id UUID REFERENCES comments (id),
    content           TEXT NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    edited_at         TIMESTAMP WITH TIME ZONE
);

CREATE TABLE votes (
    id           UUID PRIMARY KEY,
    user_id      UUID NOT NULL REFERENCES users (id),
    votable_type VARCHAR(16) NOT NULL CHECK (votable_type IN ('REVIEW', 'COMMENT')),
    votable_id   UUID NOT NULL,
    vote_value   INTEGER NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uk_votes_user_votable ON votes (user_id, votable_type, votable_id);

CREATE TABLE saved_restaurants (
    id            UUID PRIMARY KEY,
    user_id       UUID NOT NULL REFERENCES users (id),
    restaurant_id UUID NOT NULL REFERENCES restaurants (id),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uk_saved_restaurants_user_restaurant ON saved_restaurants (user_id, restaurant_id);

CREATE TABLE notifications (
    id              UUID PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users (id),
    type            VARCHAR(24) NOT NULL CHECK (type IN ('REVIEW_REPLY', 'COMMENT_REPLY', 'THREAD_REPLY')),
    actor_id        UUID REFERENCES users (id),
    comment_id      UUID NOT NULL,
    restaurant_id   UUID REFERENCES restaurants (id),
    restaurant_name VARCHAR(255),
    actor_name      VARCHAR(255),
    reply_preview   VARCHAR(300),
    read_at         TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE reports (
    id          UUID PRIMARY KEY,
    reporter_id UUID NOT NULL REFERENCES users (id),
    target_type VARCHAR(16) NOT NULL CHECK (target_type IN ('REVIEW', 'COMMENT')),
    target_id   UUID NOT NULL,
    reason      VARCHAR(32) NOT NULL CHECK (reason IN ('SPAM', 'FAKE_REVIEW', 'HARASSMENT', 'OFF_TOPIC')),
    status      VARCHAR(16) NOT NULL CHECK (status IN ('PENDING', 'REVIEWED', 'DISMISSED')),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uk_reports_reporter_target ON reports (reporter_id, target_type, target_id);

CREATE TABLE password_reset_tokens (
    id         UUID PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES users (id),
    otp_hash   VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
